import { ProductCategory } from "../../../models/common";
import { IProductOption } from "./types";

export const productOptions: { [key: string]: IProductOption } = {
  "Pewny Kapitał": {
    productName: "Pewny Kapitał",
    productCategories: [ProductCategory.Investment],
    initialValues: {
      productGuid: 6107001,
      productCategories: [],
      mainCover: { code: "PRUCAPITAL" },
      mainInsured: { insuredUuid: "", dateOfBirth: "", covers: [] },
      policyHolder: { covers: [] },
      additionalLifeAssureds: [],
      additionalCovers: [],
      wopCovers: [],
      fundContributions: [],
    },
  },
  "Komfort życia": {
    productName: "Komfort życia",
    productCategories: [ProductCategory.Protective],
    initialValues: {
      productGuid: 6101001,
      productCategories: [],
      mainCover: { code: "LIFECOV" },
      mainInsured: { insuredUuid: "", dateOfBirth: "", covers: [] },
      policyHolder: { covers: [] },
      additionalLifeAssureds: [],
      additionalCovers: [
        { code: "ACCDEATH" },
        { code: "TPDIS" },
        { code: "SI" },
        { code: "FUNCLOSS" },
        { code: "HRA" },
        { code: "PHRA" },
      ],
      wopCovers: [{ code: "WOPTPD" }, { code: "WOPSIL" }, { code: "WOPLOF" }],
      fundContributions: [],
    },
  },
  "Oszczędności bez obaw": {
    productName: "Oszczędności bez obaw",
    productCategories: [ProductCategory.Savings],
    initialValues: {
      productGuid: 6102001,
      productCategories: [],
      mainCover: { code: "PRUSAVE" },
      mainInsured: { insuredUuid: "", dateOfBirth: "", covers: [] },
      policyHolder: { covers: [] },
      additionalLifeAssureds: [],
      additionalCovers: [
        { code: "ADDLIFECOV" },
        { code: "ACCDEATH" },
        { code: "TPDIS" },
        { code: "SI" },
        { code: "FUNCLOSS" },
        { code: "HRA" },
        { code: "PHRA" },
      ],
      wopCovers: [{ code: "WOPTPD" }, { code: "WOPSIL" }, { code: "WOPLOF" }],
      fundContributions: [],
    },
  },
  "Start w życie": {
    productName: "Start w życie",
    productCategories: [ProductCategory.Savings, ProductCategory.Child],
    initialValues: {
      productGuid: 6104001,
      productCategories: [],
      mainCover: { code: "PRUCHILD" },
      mainInsured: { insuredUuid: "", dateOfBirth: "", covers: [] },
      policyHolder: { covers: [] },
      additionalLifeAssureds: [],
      additionalCovers: [{ code: "PACKTPD" }],
      wopCovers: [
        { code: "WOPTPD" },
        { code: "WOPSIL" },
        { code: "WOPLOF" },
        { code: "WOPDTH" },
      ],
      fundContributions: [],
    },
  },
  "Emerytura bez obaw": {
    productName: "Emerytura Bez Obaw",
    productCategories: [ProductCategory.Savings],
    initialValues: {
      productGuid: 6103001,
      productCategories: [],
      mainCover: { code: "PRUPENS" },
      mainInsured: { insuredUuid: "", dateOfBirth: "", covers: [] },
      policyHolder: { covers: [] },
      additionalLifeAssureds: [],
      additionalCovers: [
        { code: "ADDLIFECOV" },
        { code: "ACCDEATH" },
        { code: "TPDIS" },
        { code: "SI" },
        { code: "FUNCLOSS" },
        { code: "HRA" },
        { code: "PHRA" },
      ],
      wopCovers: [{ code: "WOPTPD" }, { code: "WOPSIL" }, { code: "WOPLOF" }],
      fundContributions: [],
    },
  },
};
